package org.koitharu.kotatsu.parsers.model

/**
 * Stub implementation of MangaParserSource for MIYO.
 *
 * In the original Kotatsu app, this enum is generated by the kotatsu-parsers KSP processor
 * from @MangaSource annotations on parser classes. MIYO does not use the KSP processor,
 * so we provide a minimal stub with a placeholder entry.
 *
 * The enum's inherent [Enum.name] property satisfies the [MangaSource.name] requirement.
 * Tachiyomi/Keiyoushi extensions use [KeiyoushiMangaSource] for identity instead.
 */
public enum class MangaParserSource(
	public override val title: String,
	public override val locale: String,
	public override val contentType: ContentType,
	public override val isBroken: Boolean,
) : MangaSource {

	MIYO_PLACEHOLDER("MIYO", "", ContentType.MANGA, false),
	;
}
