package org.koitharu.kotatsu.parsers.model

import org.koitharu.kotatsu.parsers.model.ContentType

/**
 * Stub implementation of MangaParserSource for MIYO.
 *
 * In the original Kotatsu app, this enum is generated by the kotatsu-parsers KSP processor
 * from @MangaSource annotations. MIYO does not use the KSP processor, so we provide a
 * minimal stub with a single placeholder entry.
 *
 * Tachiyomi/Keiyoushi extensions use KeiyoushiMangaSource instead of this enum,
 * so only a placeholder entry is needed to satisfy the MangaParser interface.
 */
public enum class MangaParserSource(
	public override val name: String,
	public override val title: String,
	public override val locale: String,
	public override val contentType: ContentType,
	public override val isBroken: Boolean,
) : MangaSource {

	MIYO_PLACEHOLDER("miyo_placeholder", "MIYO", "", ContentType.MANGA, false),
	;
}
